services:
  jupyter:
    build: .
    image: landmark-detection
    working_dir: /opt/landmark-detection
    command: jupyter lab --ip=0.0.0.0 --no-browser --port=8888 --NotebookApp.token='' --NotebookApp.password='' --NotebookApp.allow_origin='*' --allow-root
    ports:
      - 8889:8888
    volumes:
      - ./:/opt/landmark-detection/